config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams
  resources :groups
  resources :games
  root "game_tournaments#index"

  resources :game_tournaments do
    member do
      get :group_game
      get :play_off
      get :final
      get :matches
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game_tournament.rb
# frozen_string_literal: true

class GameTournament < ApplicationRecord
  attr_accessor :team_ids

  STATUS_DRAFT = "draft"
  STATUS_IN_PROGRESS = "in_progress"
  STATUS_DONE = "done"

  has_many :groups, dependent: :destroy
  has_many :games, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, :status, presence: true
end

app/controllers/game_tournaments_controller.rb
# frozen_string_literal: true

class GameTournamentsController < ApplicationController
  before_action :set_game_tournament, only: %i[show edit update destroy matches group_game play_off final]

  # GET /game_tournaments or /game_tournaments.json
  def index
    @game_tournaments = GameTournament.all.order(created_at: :desc)
  end

  # GET /game_tournaments/1 or /game_tournaments/1.json
  def show
    group_games
    return unless @game_tournament.status == GameTournament::STATUS_DONE

    @winner = Team.find(@game_tournament.winner_id)
    @finalist = Team.find(@game_tournament.finalist_id)
  end

  # GET /game_tournaments/new
  def new
    @teams = Team.all
    @game_tournament = GameTournament.new
  end

  # GET /game_tournaments/1/edit
  def edit; end

  def group_game
    GroupGameService.new(@game_tournament.id).generate_scores
    respond_to do |format|
      if @game_tournament.update(
        status: GameTournament::STATUS_IN_PROGRESS,
        progress: Game::PLAY_OFF_STAGE
      )

        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "tournament is in progress."
        end
        format.json { render :show, status: :ok, location: @game_tournament }
      else
        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "problem playing play group stages."
        end
        format.json { render :show, status: 400, location: @game_tournament }
      end
    end
  end

  def play_off
    PlayOffService.new(@game_tournament.id).generate_play_off_game
    respond_to do |format|
      if @game_tournament.update(progress: Game::FINAL_STAGE)
        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "tournament play-off completed."
        end
        format.json { render :show, status: :ok, location: @game_tournament }
      else
        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "problem playing play off."
        end
        format.json { render :show, status: 400, location: @game_tournament }
      end
    end
  end

  def final
    result = PlayFinalService.new(@game_tournament.id).generate_finals
    respond_to do |format|
      if @game_tournament.update(
        finalist_id: result[1], winner_id: result[0],
        status: GameTournament::STATUS_DONE, progress: Game::COMPLETED
      )
        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "tournament finals completed."
        end
        format.json { render :show, status: :ok, location: @game_tournament }
      else
        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "problem playing final."
        end
        format.json { render :show, status: 400, location: @game_tournament }
      end
    end
  end

  # POST /game_tournaments or /game_tournaments.json
  def create
    @game_tournament = GameTournament.new(game_tournament_params)
    @teams = Team.all
    respond_to do |format|
      if @game_tournament.save
        AssignTeamService.new(game_tournament_params[:team_ids], @game_tournament.id).assign
        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "tournament was successfully created."
        end
        format.json { render :show, status: :created, location: @game_tournament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @game_tournament.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /game_tournaments/1 or /game_tournaments/1.json
  def update
    respond_to do |format|
      if @game_tournament.update(game_tournament_params)
        format.html do
          redirect_to game_tournament_url(@game_tournament),
                      notice: "tournament was successfully updated."
        end
        format.json { render :show, status: :ok, location: @game_tournament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @game_tournament.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /game_tournaments/1 or /game_tournaments/1.json
  def destroy
    @game_tournament.destroy!
    respond_to do |format|
      format.html do
        redirect_to game_tournaments_url, notice: "tournament was successfully destroyed."
      end
      format.json { head(:no_content) }
    end
  end

  def matches
    @games = Game.where(game_tournament: @game_tournament)
    group_games
    group_a_matches
    group_b_matches
    play_off_matches
    final_match
  end

  def group_a_matches
    @group_a_matches = []
    @group_a_games = @games.where(
      team_a_id: @group_a_team_ids, team_b_id: @group_a_team_ids,
      progress: Game::GROUP_STAGE
    )
    generate_team_hash(@group_a_matches, @group_a_games, @group_a_teams)
  end

  def group_b_matches
    @group_b_matches = []
    @group_b_games = @games.where(
      team_a_id: @group_b_team_ids, team_b_id: @group_b_team_ids,
      progress: Game::GROUP_STAGE
    )
    generate_team_hash(@group_b_matches, @group_b_games, @group_b_teams)
  end

  def play_off_matches
    @play_off_matches = []
    @all_teams = @group_a_teams + @group_b_teams
    @play_off_games = @games.where(progress: Game::PLAY_OFF_STAGE)
    generate_team_hash(@play_off_matches, @play_off_games, @all_teams)
  end

  def final_match
    @final_matches = []
    @final_game = @games.where(progress: Game::FINAL_STAGE)
    generate_team_hash(@final_matches, @final_game, @all_teams)
  end

  private

  def generate_team_hash(matches, current_match_progress, team_list)
    current_match_progress.each do |match|
      matches << {
        team_a: team_list.find { |t| t.id == match.team_a_id },
        team_b: team_list.find { |t| t.id == match.team_b_id },
        team_a_score: match.team_a_score,
        team_b_score: match.team_b_score,
        progress: match.progress
      }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_game_tournament
    @game_tournament = GameTournament.find(params[:id])
  end

  def group_games
    groups = Group.where(game_tournament: @game_tournament)

    @group_a = groups.where(name: Group::GROUP_A)[0]
    @group_b = groups.where(name: Group::GROUP_B)[0]

    @group_a_team_ids = JSON.parse(@group_a.team_ids)
    @group_b_team_ids = JSON.parse(@group_b.team_ids)
    @group_a_teams = Team.where(id: @group_a_team_ids)
    @group_b_teams = Team.where(id: @group_b_team_ids)
  end

  # Only allow a list of trusted parameters through.
  def game_tournament_params
    params.require(:game_tournament).permit(:name, team_ids: [])
  end
end

app/helpers/game_tournaments_helper.rb
# frozen_string_literal: true

# Game Tournament
module GameTournamentsHelper
end

app/views/game_tournaments/_form.html.haml
= form_with(model: game_tournament, local: true) do |form|
  - if game_tournament.errors.any?
    #error_explanation
      %h2
        = pluralize(game_tournament.errors.count, "error")
        prohibited this game_tournament from being saved:
      %ul
        - game_tournament.errors.full_messages.each do |message|
          %li= message

  .form-group
    = form.label :name
    .row
      .col-6.col-md-6
        = form.text_field :name, class:"form-control"

  .form-group
    = form.label "Select Teams (Select multiple)"
    %br/
    .row
      = form.collection_check_boxes :team_ids, @teams, :id, :name do |b|
        .col-6.col-md-4
          = b.check_box
          = b.label

  .form-group
    = form.submit class: "btn btn-primary"

app/views/game_tournaments/edit.html.haml
%h1 Editing Game Tournament
= render 'form', game_tournament: @game_tournament
= link_to 'Show', @game_tournament
= link_to 'Back', game_tournaments_path

app/views/game_tournaments/index.html.haml
%p#notice= notice
%h1 Game tournaments
.table-responsive
  %table.table
    %thead
      %tr
        %th Name
        %th Status
        %th{colspan: "3"}
    %tbody
      - @game_tournaments.each do |game_tournament|
        %tr
          %td= game_tournament.name
          %td= game_tournament.status
          %td= link_to 'Show', game_tournament
          %td= link_to 'Edit', edit_game_tournament_path(game_tournament)
          %td= link_to 'Destroy', game_tournament, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New tournament', new_game_tournament_path, class: "btn btn-primary"

app/views/game_tournaments/matches.html.haml
:css
  p {
      font-size: 10px !important;
  }

  div {
      padding: 2px !important;
      line-height: 0px !important;
  }
%p#notice= notice
%h3 Tournament Matches
.row
  .col.col-md-6
    %h5 Group A Matches
    - @group_a_matches.each do |match|
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_a].image}", width: "15px"}/
            = match[:team_a].name
        .col.col-md-6
          %p
            = match[:team_a_score]
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_b].image}", width: "15px"}/
            = match[:team_b].name
        .col.col-md-6
          %p
            = match[:team_b_score]
      %hr/
  .col.col-md-6
    %h5 Group B Matches
    - @group_b_matches.each do |match|
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_a].image}", width: "15px"}/
            = match[:team_a].name
        .col.col-md-6
          %p
            = match[:team_a_score]
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_b].image}", width: "15px"}/
            = match[:team_b].name
        .col.col-md-6
          %p
            = match[:team_b_score]
      %hr/
%hr/
%h5 Play-Off Matches
.row
  .col.col-md-6
    - @play_off_matches.each do |match|
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_a].image}", width: "15px"}/
            = match[:team_a].name
        .col.col-md-6
          %p
            = match[:team_a_score]
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_b].image}", width: "15px"}/
            = match[:team_b].name
        .col.col-md-6
          %p
            = match[:team_b_score]
      %hr/
%hr/
%h5 Final Match
.row
  .col.col-md-6
    - @final_matches.each do |match|
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_a].image}", width: "15px"}/
            = match[:team_a].name
        .col.col-md-6
          %p
            = match[:team_a_score]
      .row
        .col.col-md-6
          %p
            %img{height: "12px", src: "#{match[:team_b].image}", width: "15px"}/
            = match[:team_b].name
        .col.col-md-6
          %p
            = match[:team_b_score]
      %hr/
%br/
= link_to 'back', :back, class: "btn btn-primary"

app/views/game_tournaments/new.html.erb
<h1>New Game tournament</h1>

<%= render 'form', game_tournament: @game_tournament %>

<%= link_to 'Back', game_tournaments_path %> |

<%= link_to 'Add Team', new_team_path(@teams), class: "btn btn-primary" %>

app/views/game_tournaments/new.html.haml
%h1 New Game tournament
= render 'form', game_tournament: @game_tournament
= link_to 'Back', game_tournaments_path
= link_to 'Add Team', new_team_path, class: "btn btn-primary"

app/views/game_tournaments/show.html.haml
%p#notice= notice
%h2
  = @game_tournament.name
%h3#teams
  %Teams>
  Groups
.Groups.row
  #GroupA.col.col-md-6
    %h3 Group A
    - @group_a_teams.each do |team|
      %h5
        %img{height: "20px", src: "#{team.image}", width: "30px"}/
        = team.name
  #GroupB.col.col-md-6
    %h3 Group B
    - @group_b_teams.each do |team|
      %h5
        %img{height: "20px", src: "#{team.image}", width: "30px"}/
        = team.name
%br/

.row
  .col.col-md-6
    %p
      %strong Status:
      = @game_tournament.status
  .col.col-md-6
    %p
      %strong Progress:
      = @game_tournament.progress
  - if @game_tournament.status == GameTournament::STATUS_DONE
    %p
      %strong Winner:
      %img{height: "20px", src: "#{@winner.image}", width: "30px"}/
      = @winner.name
    %p
      %strong Finalist:
      %img{height: "20px", src: "#{@finalist.image}", width: "30px"}/
      = @finalist.name
  - if @game_tournament.status == GameTournament::STATUS_DRAFT
    = link_to 'Start Group Matches', group_game_game_tournament_path(@game_tournament), class: "btn btn-primary"
  - if @game_tournament.progress == Game::PLAY_OFF_STAGE
    .row
      .col-md-6
        = link_to 'Play Play-Off', play_off_game_tournament_path(@game_tournament), class: "btn btn-primary"
      .col-md-6
        = link_to 'View Result', matches_game_tournament_path(@game_tournament), class: "btn btn-info"
  - if @game_tournament.progress == Game::FINAL_STAGE
    .row
      .col-md-6
        = link_to 'Play Final Match', final_game_tournament_path(@game_tournament), class: "btn btn-primary"
      .col-md-6
        = link_to 'View Result', matches_game_tournament_path(@game_tournament), class: "btn btn-info"
  - if @game_tournament.progress == Game::COMPLETED
    .row
      .col-md-6
        = link_to 'View Results', matches_game_tournament_path(@game_tournament), class: "btn btn-info"
        %br/
        
  = link_to 'Back', game_tournaments_path, class: 'btn btn-secondary'